# Generated by Django 4.1.4 on 2022-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(blank=True, choices=[('Nasr City', 'Nasr City'), ('Maadi', 'Maadi'), ('Doki', 'Doki'), ('Haram', 'Haram'), ('Faisal', 'Faisal'), ('6 October', '6 October')], max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, choices=[('Cairo', 'Cairo'), ('Giza', 'Giza')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
