# Generated by Django 4.1.4 on 2022-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_city_area_remove_location_city_client_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
    ]
