# Generated by Django 4.1.4 on 2023-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_address_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_mobile_verified',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.CharField(blank=True, choices=[('NC', 'Nasr City'), ('MA', 'Maadi'), ('DK', 'Doki'), ('HR', 'Haram'), ('FS', 'Faisal'), ('OC', '6 October')], max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
    ]
