# Generated by Django 4.1.4 on 2023-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='description',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='review',
        ),
        migrations.AlterField(
            model_name='gym',
            name='area',
            field=models.CharField(choices=[('NC', 'Nasr City'), ('MA', 'Maadi'), ('DK', 'Doki'), ('HR', 'Haram'), ('FS', 'Faisal'), ('OC', '6 October')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gender',
            field=models.CharField(choices=[('B', 'Both'), ('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
